Repository LT-Students/DigitalOffice-Kernel, pull requests merged in 2024-08, with the labels that each got.

#144 Add method for Clear Db to Cache
  LT.DigitalOffice.Kernel.RedisSupport.nuspec
  src/Kernel.RedisSupport/Helpers/CacheNotebook.cs
  src/Kernel.RedisSupport/Helpers/GlobalCacheRepository.cs
  src/Kernel.RedisSupport/Helpers/Interfaces/ICacheNotebook.cs
  src/Kernel.RedisSupport/Helpers/Interfaces/IGlobalCacheRepository.cs
  src/Kernel.RedisSupport/Helpers/RedisHelper.cs
Labels: enhancement

#145 Change RedisSupport version
  src/Kernel.RedisSupport/Kernel.RedisSupport.csproj
Labels: bug

#146 update StackExchange libs
  LT.DigitalOffice.Kernel.RedisSupport.nuspec
  src/Kernel.RedisSupport/Kernel.RedisSupport.csproj
Labels: enhancement

#148 Add Filter table to cache
  LT.DigitalOffice.Kernel.RedisSupport.nuspec
  src/Kernel.RedisSupport/Constants/Cache.cs
  src/Kernel.RedisSupport/Kernel.RedisSupport.csproj
Labels: enhancement

#149 Add docs to RedisSupport library
  LT.DigitalOffice.Kernel.RedisSupport.nuspec
  src/Kernel.RedisSupport/Configurations/RedisConfig.cs
  src/Kernel.RedisSupport/Constants/Cache.cs
  src/Kernel.RedisSupport/Extensions/RedisExtension.cs
  src/Kernel.RedisSupport/Extensions/RedisServiceExtension.cs
  src/Kernel.RedisSupport/Helpers/CacheNotebook.cs
  src/Kernel.RedisSupport/Helpers/FlushRedisDbHelper.cs
  src/Kernel.RedisSupport/Helpers/GlobalCacheRepository.cs
  src/Kernel.RedisSupport/Helpers/Interfaces/ICacheHelper.cs
  src/Kernel.RedisSupport/Helpers/Interfaces/ICacheNotebook.cs
  src/Kernel.RedisSupport/Helpers/Interfaces/IGlobalCacheRepository.cs
  src/Kernel.RedisSupport/Helpers/RedisHelper.cs
  src/Kernel.RedisSupport/Kernel.RedisSupport.csproj
Labels: documentation

#150 Fix flush redis
  LT.DigitalOffice.Kernel.RedisSupport.nuspec
  src/Kernel.RedisSupport/Helpers/FlushRedisDbHelper.cs
  src/Kernel.RedisSupport/Kernel.RedisSupport.csproj
Labels: bug

#151 Fix crashing services
  LT.DigitalOffice.Kernel.RedisSupport.nuspec
  src/Kernel.RedisSupport/Helpers/RedisHelper.cs
  src/Kernel.RedisSupport/Kernel.RedisSupport.csproj
Labels: bug

#152 Add Redis sets support
  LT.DigitalOffice.Kernel.RedisSupport.nuspec
  src/Kernel.RedisSupport/Helpers/Interfaces/ICacheHelper.cs
  src/Kernel.RedisSupport/Helpers/RedisHelper.cs
  src/Kernel.RedisSupport/Kernel.RedisSupport.csproj
Labels: enhancement
